import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Jaedon',
      email: 'admin@exmaple.com',
      password: bcrypt.hashSync('123456', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Puma',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 100,
      },
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456', 8),
    },
  ],
  categories: ['Shirts', 'Pants', 'Shoes'],
  products: [
    {
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      images: ['/images/p2.jpg', '/images/p3.jpg'],
      reviews: [
        { name: 'Jaedon', comment: 'It is great', rating: 4.5 },
        { name: 'Basir', comment: 'It is good', rating: 3.5 },
      ],
      price: '60',
      brand: 'Nike',
      rating: 4.5,
      numReviews: 12,

      countInStock: 30,
      description: 'sample description',
    },
    {
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      images: [],
      price: 70,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 123,
      countInStock: 10,
      description: 'sample description',
    },
    {
      name: 'Lacoste Free Size Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      images: [],
      price: '610',
      brand: 'Lacoste',
      rating: 4.1,
      numReviews: 133,
      countInStock: 10,
      description: 'sample description',
    },
    {
      name: 'Nike Slim Pants',
      category: 'Pants',
      image: '/images/p4.jpg',
      images: [],
      price: '600',
      brand: 'Nike',
      rating: 3.5,
      numReviews: 124,
      countInStock: 10,
      description: 'sample description',
    },
    {
      name: 'Lacoste Fit Pants',
      category: 'Pants',
      image: '/images/p5.jpg',
      images: [],
      price: '64',
      brand: 'Lacoste',
      rating: 4.7,
      numReviews: 125,
      countInStock: 10,
      description: 'sample description',
    },
    {
      name: 'Under Armour Pants',
      category: 'Pants',
      image: '/images/p6.jpg',
      images: [],
      price: '68',
      brand: 'Under Armour',
      rating: 4.6,
      numReviews: 126,
      countInStock: 0,
      description: 'sample description',
    },
  ],
};

export default data;
