const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'shirt',
      image: '/images/p1.jpg',
      price: '60',
      brand: 'Nike',
      rating: 4.5,
      numReviews: 12,
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      category: 'shirt',
      image: '/images/p2.jpg',
      price: 70,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 123,
    },
    {
      _id: '3',
      name: 'Lacoste Free Size Shirt',
      category: 'shirt',
      image: '/images/p3.jpg',
      price: '610',
      brand: 'Lacoste',
      rating: 4.1,
      numReviews: 133,
    },
    {
      _id: '4',
      name: 'Nike Slim Pants',
      category: 'pants',
      image: '/images/p4.jpg',
      price: '600',
      brand: 'Nike',
      rating: 3.5,
      numReviews: 124,
    },
    {
      _id: '5',
      name: 'Lacoste Fit Pants',
      category: 'pants',
      image: '/images/p5.jpg',
      price: '64',
      brand: 'Lacoste',
      rating: 4.7,
      numReviews: 125,
    },
    {
      _id: '6',
      name: 'Under Armour Pants',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: '68',
      brand: 'Under Armour',
      rating: 4.6,
      numReviews: 126,
    },
  ],
};

export default data;
